import type { AdminColumnDefinition } from "../../types";

export const ETAT_OPTIONS = [
  { label: "Validée", value: "Validée", color: "green" },
  { label: "Nouveau", value: "Nouveau", color: "blue" },
  { label: "Non Validée", value: "Non Validée", color: "orange" },
  { label: "Supprimée", value: "Supprimée", color: "red" },
];

export const PREMIUM_OPTIONS = [
  { label: "Oui", value: "true", color: "green" },
  { label: "Non", value: "false", color: "red" },
];

export const CANDIDATS_COLUMNS: AdminColumnDefinition[] = [
  {
    id: "id",
    label: "ID",
    fieldName: "id",
    type: "NUMBER",
    size: 70,
    position: 0,
    isVisible: false,
    isFilterable: true,
    isSortable: true,
  },
  {
    id: "nomComplet",
    label: "Nom complet",
    fieldName: "nomComplet",
    type: "TEXT",
    size: 200,
    position: 1,
    isLabelIdentifier: true,
    isVisible: true,
    isFilterable: true,
    isSortable: true,
    customRender: true, // Rendu custom avec photo
  },
  {
    id: "email",
    label: "Email",
    fieldName: "email",
    type: "EMAIL",
    size: 220,
    position: 3.5,
    isVisible: true,
    isFilterable: true,
    isSortable: true,
    isEditable: true,
    editTarget: "user",
    apiFieldName: "email",
    customRender: true, // InlineEditCell
  },

  {
    id: "gsm",
    label: "GSM",
    fieldName: "gsm",
    type: "PHONE",
    size: 130,
    position: 4,
    isVisible: true,
    isFilterable: false,
    isSortable: true,
    isEditable: true,
    editTarget: "user",
    apiFieldName: "num_tel",
    customRender: true, // InlineEditCell
  },
  {
    id: "cv",
    label: "CV",
    fieldName: "cv",
    type: "CV_SCORE",
    size: 100,
    position: 5,
    isVisible: true,
    isFilterable: true,
    isSortable: false,
    isEditable: false,
    options: [
      { label: "Sans CV", value: "sans_cv", color: "red" },
      { label: "Nouveau (0%)", value: "Nouveau", color: "blue" },
      { label: "Validé", value: "Validée", color: "green" },
      { label: "Non validé", value: "Non_Validée", color: "orange" },
    ],
  },
  {
    id: "ville",
    label: "Ville",
    fieldName: "ville",
    type: "RELATION",
    size: 120,
    position: 7,
    isVisible: true,
    isFilterable: true,
    isSortable: false,
    isEditable: true,
    editTarget: "user",
    apiFieldName: "city_id",
  },
  {
    id: "nomEcole",
    label: "École",
    fieldName: "nomEcole",
    type: "RELATION",
    size: 150,
    position: 8,
    isVisible: true,
    isFilterable: true,
    isSortable: false,
    isEditable: true,
    editTarget: "entity",
    apiFieldName: "ecole_id",
  },
  {
    id: "niveauEtudes",
    label: "Niveau d'études",
    fieldName: "niveauEtudes",
    type: "SELECT",
    size: 130,
    position: 9,
    isVisible: true,
    isFilterable: true,
    isSortable: true,
    isEditable: true,
    editTarget: "entity",
    apiFieldName: "niveau_formation",
    options: [],
  },
  {
    id: "typeContrat",
    label: "Type(s) de contrat",
    fieldName: "typeContrat",
    type: "MULTI_SELECT",
    size: 150,
    position: 10,
    isVisible: true,
    isFilterable: true,
    isSortable: false,
    isEditable: false,
    editTarget: "entity",
    apiFieldName: "typeContrats",
  },
  {
    id: "typeStage",
    label: "Type(s) de stage",
    fieldName: "typeStage",
    type: "MULTI_SELECT",
    size: 140,
    position: 11,
    isVisible: false,
    isFilterable: true,
    isSortable: false,
    isEditable: false,
    editTarget: "entity",
    apiFieldName: "typeStages",
  },
  {
    id: "premium",
    label: "Premium",
    fieldName: "premium",
    type: "PREMIUM_BADGE",
    size: 52,
    minSize: 40,
    position: 13,
    isVisible: true,
    isFilterable: true,
    isSortable: false,
    isEditable: true,
    editTarget: "entity",
    apiFieldName: "premium",
    options: PREMIUM_OPTIONS,
  },
  {
    id: "etat",
    label: "État",
    fieldName: "etat",
    type: "SELECT",
    size: 100,
    position: 15,
    isVisible: true,
    isFilterable: true,
    isSortable: true,
    isEditable: true,
    editTarget: "entity",
    apiFieldName: "etat",
    options: ETAT_OPTIONS,
    customRender: true, // EditDropdownCell
  },
  {
    id: "dateConnexion",
    label: "D.connexion",
    fieldName: "dateConnexion",
    type: "DATE",
    size: 110,
    position: 16,
    isVisible: true,
    isFilterable: false,
    isSortable: true,
    isEditable: false,
  },
  {
    id: "inscritLe",
    label: "Inscrit le",
    fieldName: "inscritLe",
    type: "DATE",
    size: 110,
    position: 17,
    isVisible: true,
    isFilterable: false,
    isSortable: true,
    isEditable: false,
  },
  {
    id: "loginSource",
    label: "Source connexion",
    fieldName: "loginSource",
    type: "TEXT",
    size: 52,
    minSize: 40,
    position: 2,
    isVisible: true,
    isFilterable: false,
    isSortable: false,
    isEditable: false,
    customRender: true,
  },
];
